
[general]
	leaves_decay_particles = true
	falling_leaf_particles = true
	decay_sound = true
	#Range: 0.0 ~ 1.0
	falling_leaf_rate = 0.08
	#Range: 0.0 ~ 1.0
	rainy_falling_leaf_rate = 0.2
	#Range: 0.0 ~ 1.0
	stormy_falling_leaf_rate = 0.4

