blank_issues_enabled: true
issue_templates:
  - name: 🐛 Bug Report / Сообщение об ошибке
    description: Report a bug or crash / Сообщите об ошибке или сбое
    file: bug-report.yml
  - name: 💡 Content Suggestion / Предложение о контенте
    description: Suggest adding or removing content / Предложите добавить или удалить контент
    file: content-suggestion.yml
  - name: ⚙ Config Tweak / Предложение настройки
    description: Request a config tweak / Предложите изменить отдельные настройки
    file: setting-request.yml
