
#Please be advised that certain thirst-related options are world-specific and are located in <Path to your world folder>/serverconfig/toughasnails-server.toml.
[general]
	#The threshold at which exhaustion causes a reduction in hydration and the thirst bar.
	exhaustion_threshold = 8.0

[drink_options]
	#Thirst restored from drinking with hands.
	hand_drinking_thirst = 3
	#Hydration restored from drinking with hands.
	hand_drinking_hydration = 0.5

[biome_options]

	#The types of water found in biomes from Vanilla and other mods.
	[[biome_options.biome_water_entries]]
		location = "minecraft:badlands"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "minecraft:eroded_badlands"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "minecraft:wooded_badlands"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "minecraft:mangrove_swamp"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "minecraft:mushroom_fields"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "minecraft:deep_dark"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "biomesoplenty:bayou"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "biomesoplenty:bog"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "biomesoplenty:fungal_jungle"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "biomesoplenty:highland_moor"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "biomesoplenty:marsh"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "biomesoplenty:muskeg"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "biomesoplenty:ominous_woods"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "biomesoplenty:volcanic_plains"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "biomesoplenty:volcano"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "biomesoplenty:wasteland"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "biomesoplenty:wetland"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "biomesoplenty:wooded_wasteland"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "terralith:ice_marsh"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "terralith:mirage_isles"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "terralith:orchid_swamp"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "terralith:savanna_badlands"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "terralith:snowy_badlands"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "terralith:volcanic_crater"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "terralith:volcanic_peaks"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "terralith:warped_mesa"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "terralith:white_mesa"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "terralith:cave/fungal_caves"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "terralith:cave/underground_jungle"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "bro:void/void"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "bro:void/void_below"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "bro:void/void_inverse"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "bro:void/void_inverse_below"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "deeperdarker:blooming_caverns"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "deeperdarker:deeplands"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "deeperdarker:echoing_forest"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "deeperdarker:overcast_columns"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "biomesoplenty:rainbow_hills"
		type = "PURIFIED"

	[[biome_options.biome_water_entries]]
		location = "minecraft:frozen_peaks"
		type = "PURIFIED"

	[[biome_options.biome_water_entries]]
		location = "terralith:yellowstone"
		type = "PURIFIED"

	[[biome_options.biome_water_entries]]
		location = "terralith:skylands_winter"
		type = "PURIFIED"

	[[biome_options.biome_water_entries]]
		location = "terralith:frozen_cliffs"
		type = "PURIFIED"

	[[biome_options.biome_water_entries]]
		location = "terralith:glacial_chasm"
		type = "PURIFIED"

	[[biome_options.biome_water_entries]]
		location = "terralith:cave/ice_caves"
		type = "PURIFIED"

	[[biome_options.biome_water_entries]]
		location = "terralith:cave/frostfire_caves"
		type = "PURIFIED"

	[[biome_options.biome_water_entries]]
		location = "terralith:cave/mantle_caves"
		type = "PURIFIED"

	[[biome_options.biome_water_entries]]
		location = "bro:saturated/cave/glacial_carve"
		type = "PURIFIED"

	[[biome_options.biome_water_entries]]
		location = "bro:saturated/cave/underground_jungle"
		type = "PURIFIED"

	[[biome_options.biome_water_entries]]
		location = "bro:saturated/freezer"
		type = "PURIFIED"

	[[biome_options.biome_water_entries]]
		location = "bro:saturated/the_enchanted"
		type = "PURIFIED"

[toggles]
	#Enable or disable thirst.
	enable_thirst = true
	#Enable or disable hand drinking.
	enable_hand_drinking = true
	#Remove source blocks when filling the canteen.
	remove_source_blocks = false
	#Prevent sprinting when thirsty.
	thirst_prevent_sprint = true
	#Prevent health regeneration when thirsty.
	thirst_prevent_health_regen = true

