
[Timers]
	#Modify the timers for the surface (to reduce or increase them), based on the general timer set (e.g. spawn timer of 300 seconds -> 0.3 turns it into 90 seconds and 1.7 turns it into 510 seconds for the surface)
	#Range: 0.0 ~ 5.0
	surface_timer_multiplier = 1.0

	[Timers.Spawn]
		#Minimum time between spawns in seconds
		#Range: 0 ~ 86400
		can_spawn_min = 360
		#Maximum time between spawns in seconds
		#Range: 0 ~ 86400
		can_spawn_max = 1800
		#Chance for a spawn cooldown to occur
		#Range: 0.0 ~ 1.0
		can_spawn_cooldown_chance = 0.05
		#Spawn cooldown length in seconds
		#Range: 0 ~ 86400
		can_spawn_cooldown = 1200

	[Timers.Noise]
		#Minimum time between noise occurrences in seconds
		#Range: 0 ~ 86400
		reset_noise_min = 360
		#Maximum time between noise occurrences in seconds
		#Range: 0 ~ 86400
		reset_noise_max = 480

	[Timers.Leave]
		#Time (in seconds) it takes for the GoatMan to leave
		#Range: 1 ~ 6000
		time_until_leave = 240
		#Time (in seconds) it takes for the GoatMan to leave once a chase begins
		#Range: 1 ~ 600
		time_until_leave_chase = 25

["Spawn Conditions"]
	#The spawn chance per tick (once the spawn timer is finished)
	#Range: 0.0 ~ 1.0
	spawn_chance_per_tick = 0.01
	#Depth at which the GoatMan can start to spawn
	spawn_height = 384
	#Whether the GoatMan can spawn on the surface or not
	allow_surface_spawn = true
	#The maximum sky light level the GoatMan can spawn at
	#Range: 0 ~ 15
	sky_light_level = 10
	#The maximum block light level the GoatMan can spawn at
	#Range: 0 ~ 15
	block_light_level = 8
	#The maximum amount of GoatMan which can exist at the same time
	#Range: 0 ~ 100
	maximum_amount = 3
	#How close to players the GoatMan is allowed to spawn (in blocks)
	#Range: 0 ~ 64
	spawn_distance = 24
	#If set to true the GoatMan will try to find a spawn position with a possible path to the player
	check_path_to_spawn = true

	["Spawn Conditions".Dimensions]
		#The dimensions where the GoatMan can spawn in (Whitelist)
		dimension_whitelist = ["minecraft:overworld", "bro:saturated"]

	["Spawn Conditions".Biomes]
		#If you don't want to create a datapack to configure the biomes
		override_biome_datapack_config = false
		#Use the surface biome list either as white- or blacklist
		surface_biomes_is_whitelist = true
		#Either white- or blacklist of the surface biomes the GoatMan can spawn in (Syntax: modid:biome, e.g. `minecraft:plains`)
		surface_biomes = ["minecraft:frozen_peaks", "minecraft:jagged_peaks", "minecraft:snowy_slopes", "minecraft:desert", "minecraft:badlands", "minecraft:eroded_badlands", "minecraft:wooded_badlands", "minecraft:savanna", "minecraft:savanna_plateau", "minecraft:windswept_savanna", "minecraft:taiga", "minecraft:frozen_river", "minecraft:snowy_plains", "minecraft:snowy_beach", "minecraft:snowy_taiga", "minecraft:old_growth_pine_taiga", "minecraft:grove", "minecraft:ice_spikes", "bro:saturated/basalt_climb", "bro:saturated/bone_canyon", "bro:saturated/crystallized_peaks", "bro:saturated/verdant_spires", "bro:saturated/freezer", "bro:saturated/stranger_flats", "bro:saturated/cave/bone_cavern", "bro:saturated/cave/empty", "bro:saturated/cave/littoral_hollow", "terralith:alpine_highlands", "terralith:alpine_grove", "terralith:ancient_sands", "terralith:arid_highlands", "terralith:bryce_canyon", "terralith:blooming_plateau", "terralith:desert_canyon", "terralith:desert_oasis", "terralith:desert_spires", "terralith:emerald_peaks", "terralith:forested_highlands", "terralith:frozen_cliffs", "terralith:glacial_chasm", "terralith:gravel_desert", "terralith:haze_mountain", "terralith:highlands", "terralith:jungle_mountains", "terralith:lush_desert", "terralith:lush_valley", "terralith:moonlight_grove", "terralith:painted_mountains", "terralith:red_oasis", "terralith:rocky_jungle", "terralith:rocky_mountains", "terralith:sandstone_valley", "terralith:savanna_badlands", "terralith:savanna_slopes", "terralith:scarlet_mountains", "terralith:siberian_grove", "terralith:siberian_taiga", "terralith:snowy_badlands", "terralith:stony_spires", "terralith:temperate_highlands", "terralith:tropical_jungle", "terralith:warped_mesa", "terralith:white_mesa", "terralith:windswept_spires", "terralith:yellowstone", "terralith:yosemite_cliffs", "terralith:cave/andesite_caves", "terralith:cave/diorite_caves", "terralith:cave/granite_caves", "terralith:cave/ice_caves", "terralith:cave/infested_caves"]

[Behaviour]
	#The distance in blocks at which the GoatMan can detect whether a player is looking at it or not
	#Range: 0 ~ 128
	spotting_range = 80
	#Whether the GoatMan can climb or not
	can_climb = true
	#Allow the GoatMan to follow vanilla riding logic (e.g. boats)
	allow_riding = false
	#Whether invisible players can be targets or not
	target_invisible = false

[Attributes]
	#Maximum Armor
	#Range: 0.0 ~ 20.0
	maximum_armor = 2.0
	#Maximum Health
	#Range: 1.0 ~ 500.0
	maximum_health = 60.0
	#Attack Damage
	#Range: 0.0 ~ 50.0
	attack_damage = 15.0
	#Movement Speed
	#Range: 0.0 ~ 5.0
	movement_speed = 0.6
	#Depth Strider (movement speed in water) Bonus
	#Range: 0.0 ~ 3.0
	depth_strider_bonus = 2.0

[Misc]
	#Only play the ambient noises to the current (spawn) target (Note: The target can change when a spawn attempt is not successful)
	only_play_noise_to_target = false

